### ISSUE TITLE
Get-AzConsumptionUsageDetail Bad Request

### ISSUE THREAD

**Issue by Tiberriver256** [markwragg/PowerShell-AzCostTools#6]
Hey 👋

I ran into [this issue](https://github.com/Azure/azure-powershell/issues/12561) and I'm wondering if you have any good alternatives besides that cmdlet to use with this module?

**Comment by markwragg** [comment]
Unfortunately at the moment this module doesn't support anything other than `Get-AzConsumptionUsageDetail`. My plan at some point was to add some functionality to load in exported cost data, so if you can get your costs out to a CSV via the Azure Portal (or CSP portal) then we can load it in that way. It would be helpful if someone could share an example of what exported CSP costs look like so I know the header names.

**Comment by markwragg** [comment]
Hey I hadn't looked properly at that issue you linked before, and didn't see the function @BrianStringFellow added that works around the issue. I've now added this to AzCostTools, so it will automatically fall back to it if it gets a Bad Request result, or you can force use of it by specifying `-EaSubscription`. If your Subscriptions are legacy you might then also need to specify `-EaSubscriptionKind legacy` (it assumes modern by default).

These changes should be in version [0.0.4](https://www.powershellgallery.com/packages/AzCostTools/0.0.4) of the AzCostTools module, give it a go and let me know if you have any issues.

**Comment by markwragg** [comment]
Please use version 0.0.5 of the module, I discovered that what I had added was only returning costs in USD, the latest version now returns cost in billing currency.

**Comment by Tiberriver256** [comment]
Thank you!
